local M = {}

function M.set(hl, colors)
	hl.set('CmpDocumentationBorder', { link = 'VertSplit' })
	hl.set('CmpItemAbbrDefault', { fg = hl.get('Pmenu').fg })
	hl.set('CmpItemAbbrMatchDefault', { fg = colors.fg.hex })
	hl.set('CmpItemAbbrMatchFuzzyDefault', { fg = colors.fg.hex })
	hl.set('CmpItemKindDefault', { link = 'Type' })
	hl.set('CmpItemKindClassDefault', { link = 'Type' })
	hl.set('CmpItemKindColorDefault', { link = 'Label' })
	hl.set('CmpItemKindConstantDefault', { link = 'Constant' })
	hl.set('CmpItemKindConstructorDefault', { link = 'Function' })
	hl.set('CmpItemKindEnumDefault', { link = 'Constant' })
	hl.set('CmpItemKindEnumMemberDefault', { link = 'Constant' })
	hl.set('CmpItemKindEventDefault', { link = 'Repeat' })
	hl.set('CmpItemKindFieldDefault', { link = 'Identifier' })
	hl.set('CmpItemKindFileDefault', { link = 'Directory' })
	hl.set('CmpItemKindFolderDefault', { link = 'CmpItemKindFileDefault' })
	hl.set('CmpItemKindFunctionDefault', { link = 'Function' })
	hl.set('CmpItemKindInterfaceDefault', { link = 'Type' })
	hl.set('CmpItemKindKeywordDefault', { link = 'Keyword' })
	hl.set('CmpItemKindMethodDefault', { link = 'CmpItemKindFunctionDefault' })
	hl.set('CmpItemKindModuleDefault', { link = 'Function' })
	hl.set('CmpItemKindOperatorDefault', { link = 'Operator' })
	hl.set('CmpItemKindPropertyDefault', { link = 'CmpItemKindFieldDefault' })
	hl.set('CmpItemKindReferenceDefault', { link = 'StorageClass' })
	hl.set('CmpItemKindSnippetDefault', { link = 'Special' })
	hl.set('CmpItemKindStructDefault', { link = 'Structure' })
	hl.set('CmpItemKindTextDefault', { link = 'String' })
	hl.set('CmpItemKindTypeParameterDefault', { link = 'Type' })
	hl.set('CmpItemKindUnitDefault', { link = 'CmpItemKindStructDefault' })
	hl.set('CmpItemKindValueDefault', { link = 'CmpItemKindConstantDefault' })
	hl.set('CmpItemKindVariableDefault', { link = 'Identifier' })
	hl.set('CmpItemMenu', { fg = colors.fg3.hex })
	hl.set('CmpScrollThumb', { link = 'PmenuThumb' })
end

return M
