local M = {}

function M.set(hl, colors)
    hl.set("CmpDocumentationBorder", { bg = hl.get("Pmenu").bg })
    hl.set("CmpItemAbbr", { fg = hl.get("Pmenu").fg })
    hl.set("CmpItemAbbrMatch", { fg = colors.fg })
    hl.set("CmpItemAbbrMatchFuzzy", { fg = colors.fg })
    hl.set("CmpItemKind", { fg = hl.get("Type").fg })
    hl.set("CmpItemKindClass", { fg = hl.get("Type").fg })
    hl.set("CmpItemKindColor", { fg = hl.get("Label").fg })
    hl.set("CmpItemKindConstant", { fg = hl.get("Constant").fg })
    hl.set("CmpItemKindConstructor", { fg = hl.get("Function").fg })
    hl.set("CmpItemKindEnum", { fg = hl.get("Constant").fg })
    hl.set("CmpItemKindEnumMember", { fg = hl.get("Constant").fg })
    hl.set("CmpItemKindEvent", { fg = hl.get("Repeat").fg })
    hl.set("CmpItemKindField", { fg = hl.get("Identifier").fg })
    hl.set("CmpItemKindFile", { fg = hl.get("Directory").fg })
    hl.set("CmpItemKindFolder", { fg = hl.get("CmpItemKindFile").fg })
    hl.set("CmpItemKindFunction", { fg = hl.get("Function").fg })
    hl.set("CmpItemKindInterface", { fg = hl.get("Type").fg })
    hl.set("CmpItemKindKeyword", { fg = hl.get("Keyword").fg })
    hl.set("CmpItemKindMethod", { fg = hl.get("CmpItemKindFunction").fg })
    hl.set("CmpItemKindModule", { fg = hl.get("Function").fg })
    hl.set("CmpItemKindOperator", { fg = hl.get("Operator").fg })
    hl.set("CmpItemKindProperty", { fg = hl.get("CmpItemKindField").fg })
    hl.set("CmpItemKindReference", { fg = hl.get("StorageClass").fg })
    hl.set("CmpItemKindSnippet", { fg = hl.get("Special").fg })
    hl.set("CmpItemKindStruct", { fg = hl.get("Structure").fg })
    hl.set("CmpItemKindText", { fg = hl.get("String").fg })
    hl.set("CmpItemKindTypeParameter", { fg = hl.get("Type").fg })
    hl.set("CmpItemKindUnit", { fg = hl.get("CmpItemKindStruct").fg })
    hl.set("CmpItemKindValue", { fg = hl.get("CmpItemKindConstant").fg })
    hl.set("CmpItemKindVariable", { fg = hl.get("Identifier").fg })
    hl.set("CmpItemMenu", { fg = colors.fg3 })
    hl.set("CmpScrollThumb", { fg = hl.get("PmenuThumb").fg })
end

return M
